### ISSUE TITLE
flutter_platform_widgets needs to be upgraded to fix error he getter 'fullObstruction' isn't defined for the class 'ObstructingPreferredSizeWidget'.

### ISSUE THREAD

**Issue by ganesansankara** [fluttercommunity/native_widgets#7]
flutter_platform_widget has to be upgraded to latest version to fix the following error

platform_widgets-0.20.2/lib/src/platform_scaffold.dart:229:38: Error: The getter 'fullObstruction' isn't defined for the class 'ObstructingPreferredSizeWidget'.

**Comment by davismwfl** [comment]
FWIW it does appear just updating flutter_platform_widget to 0.30.1 in the pub_cache copy of native_widgets pubspec and then performing a get on packages does resolve the issue and everything seems to operate properly.

**Comment by sjmcdowall** [comment]
@davismwfl  -- do you have couple of steps on how / what you did exactly/ I'm having the same error but not sure of the steps you are proposing as a temp work around .. 

I ask because I tried to do what you said but I still get an error and it's still (something is) pointing to 0.20.1 of platform_widgets .. 

TIA

**Comment by davismwfl** [comment]
@sjmcdowall -- in your flutter install directory you will have a .pub-cache.  

Edit flutter/.pub-cache/hosted/pub.dartlang.org/native_widgets-1.3.5/pubspec.yaml and update the dependencies to show flutter_platform_widgets: ^0.30.1. 

Afterwards do a get packages then a flutter clean and do a build.  Technically the get might be optional, but these are the steps I did and it all worked. 

Obviously this isn't ideal, but it does work and gets around the issue for now until native_widgets is updated.

**Comment by sjmcdowall** [comment]
@davismwfl -- I just went and forked this project and fixed the dependency there and then issued a PR for it.   Until the PR is done anyone can just use 

  native_widgets:
    git:
      url: git://github.com/sjmcdowall/native_widgets.gi

in their pubspec

**Comment by ganesansankara** [comment]
@rodydavis : Hello, when will this PR merged in the next release?

**Comment by rodydavis** [comment]
Merging now👍🏼

**Comment by rodydavis** [comment]
Merged and Published with version 1.3.6. Sorry about the delay. if I don't respond feel free to ping my email next time.

**Comment by ganesansankara** [comment]
Speedy response. Appreciate that. Happy New Year 2020

**Comment by rodydavis** [comment]
Likewise!
